spring:
  application:
    name: Oper

  datasource:
    url: jdbc:mysql://localhost:3306/oper?createDatabaseIfNotExist=true
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver
    tomcat:
      max-wait: 3000
      max-active: 50
      test-on-borrow: true

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext